GET http://localhost:4000/movie-api/movie

###

GET http://localhost:4000/user-api/user

###
POST http://localhost:4000/user-api/login
Content-Type: application/json

{
    "username":"shubham",
    "password":"shubham"  
}

###
POST http://localhost:4000/user-api/admin
Content-Type: application/json

{
    "username":"shubham",
    "password":"shubham"
}

